security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\UserGame
                property: username
    encoders:
        App\Entity\UserGame:
            algorithm: auto


    access_denied_url: /login
    role_hierarchy:
        ROLE_USER:        ROLE_NEW
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]



    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            http_basic:
                realm: Secured Area



                # where to redirect after logout
               #  target: /login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:

        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

